#配置服务
server:
  port: 8080 #端口号
  servlet:
    context-path: /kai #项目路径
    
#配置mybatis
mybatis:
  #定义Mapper的XML路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #配置文件路径
  config-location: classpath:mapper/config/mybatis-Configuration.xml
  #定义别名扫描的包
  type-aliases-package: com.yk.po
 
#JDBC配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kai?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kai
    type: com.alibaba.druid.pool.DruidDataSource
#Druid配置    
    druid:
      initial-size: 3 #初始化连接数
      min-idle: 5 #最小连接数
      max-active: 10 #最大连接数
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
  # 禁用缓存
  thymeleaf:
    cache: false
  #ActiveMQ配置
#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#    pool:
#      #是否启用连接池
#      enabled: true
#      #连接池最大连接数配置
#      max-connections: 50
#  jms:
#    #是否使用发布订阅模式，默认为false，即默认点对点模式
#    pub-sub-domain: true
#    template:
#      default-destination: activemq.default.destination
    
    
#日志配置
logging:
  level:
    org.springframework: info
    root: info
    org.mybatis: info
    #打印Mybatis sql语句
    com.yk.dao: debug
    
yk:
  ip: 130.10.5.122
  name: yk-server
