#配置服务
server:
  port: 8080 #端口号
  servlet:
    context-path: /kai #项目路径
    
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mapper/config/mybatis-Configuration.xml
  type-aliases-package: com.yk.po
 
#JDBC配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kai?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kai
    type: com.alibaba.druid.pool.DruidDataSource
#Druid配置    
    druid:
      initial-size: 3 #初始化连接数
      min-idle: 5 #最小连接数
      max-active: 10 #最大连接数
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
  # 禁用缓存
  thymeleaf:
    cache: false